name: TouchGFX Sitemap Scraper

on:
  schedule:
    - cron: '15 * * * *' # '0 */8 * * *'  # Every 8 hours
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r ./touchgfx/requirements.txt

      - name: Run TouchGFX Sitemap Scraper
        run: python ./touchgfx/app.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: touchgfx-csv
          path: ./touchgfx/touchgfx-*.csv
          if-no-files-found: error

concurrency:
  group: touchgfx-scraper
  cancel-in-progress: false
